name: Build and Test

on:
  push:
    branches:
      - '**'
  # pull_request:
  #   branches:
  #     - '**'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Start RabbitMQ
        uses: namoshek/rabbitmq-github-action@v1
        with:
          ports: '5672:5672 15672:15672'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
      - name: Build
        run: dotnet build --no-restore
      - name: Run tests
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.CONNECTION_STRING }}
          Auth__Domain: "${{ secrets.AUTH0_DOMAIN }}"
          Auth__Audience: "${{ secrets.AUTH0_AUDIENCE }}"
        run: dotnet test ./PostIntegrationTests/PostIntegrationTests.csproj