name: Deploy to AKS with Kubeconfig

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Write Kubeconfig to File
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG" > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml
        echo "KUBECONFIG set to $(pwd)/kubeconfig.yaml"
        kubectl --kubeconfig=$(pwd)/kubeconfig.yaml

    - name: Log in to ACR
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Prepare Deployment File
      run: |
        sed -i "s|PLACEHOLDER_AZURE_CONTAINER_REGISTRY|${{ secrets.AZURE_CONTAINER_REGISTRY }}|g" deployment.yaml
        IMAGE_TAG=${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/as6-2_osso_post_service:main
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG
    
    - name: Deploy to AKS
      run: |
        kubectl --kubeconfig=$(pwd)/kubeconfig.yaml apply -f deployment.yaml --validate=false
        kubectl --kubeconfig=$(pwd)/kubeconfig.yaml rollout status deployment/post-service
